name: wf-cd-staging
on:
  push:
    branches:
      - "release/**"
jobs:
  build-staging-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build Website for release
        run: npx parcel build "./src/index.html" --dist-dir "./release" --public-url "./"
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./release"
          name: "build-artifact-development"
          
  deploy-staging-job:
    needs: "build-release-job"
    environment: "staging-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: DeployDevelopment Artifacts
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-development"
          token: ${{github.token}}