name: wf-ci-production
on:
  pull_request:
    branches:
      - production
jobs:
  ci-production-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Lint HTML and CSS Code
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Build Artifact
        run: |
          npx parcel build "./src/index.html" --dist-dir "./production" --public-url "./"
